# Generated by Django 4.1 on 2025-06-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_vuelo', models.CharField(max_length=100)),
                ('origen', models.TextField()),
                ('destino', models.TextField()),
                ('hora_salida', models.DateTimeField()),
                ('hora_llegada', models.DateTimeField()),
                ('fecha_salida', models.DateField()),
                ('fecha_llegada', models.DateField()),
            ],
        ),
    ]
