# Generated by Django 4.1 on 2025-06-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelo',
            name='hora_llegada',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='hora_salida',
            field=models.TimeField(),
        ),
    ]
